import jsPDF from "jspdf";
import "jspdf-autotable";

export const generatePDFReport = async (scanData, type) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(102, 126, 234);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("PhishGuard Security Report", 20, 25);

  // Reset color
  doc.setTextColor(0, 0, 0);

  // Report metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Report ID: ${scanData.id || "N/A"}`, 20, 55);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 62);
  doc.text(
    `Scan Type: ${type === "url" ? "URL Scan" : "Message Scan"}`,
    20,
    69,
  );

  // Scan Content
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Scan Information", 20, 85);

  const scanInfo = [
    ["Content", scanData.content || scanData.message || "N/A"],
    ["Classification", scanData.classification || "N/A"],
    ["Risk Score", `${scanData.riskScore}%`],
    ["Confidence", `${((scanData.confidence || 0.5) * 100).toFixed(1)}%`],
    ["Date", new Date(scanData.date || Date.now()).toLocaleString()],
  ];

  doc.autoTable({
    startY: 90,
    head: [["Field", "Value"]],
    body: scanInfo,
    theme: "striped",
    headStyles: { fillColor: [102, 126, 234] },
    margin: { left: 20, right: 20 },
    styles: { fontSize: 10 },
  });

  let currentY = doc.lastAutoTable.finalY + 15;

  // Explanation
  doc.setFontSize(14);
  doc.text("Analysis Explanation", 20, currentY);
  currentY += 8;

  doc.setFontSize(10);
  const explanation = doc.splitTextToSize(
    scanData.explanation || "No explanation available",
    170,
  );
  doc.text(explanation, 20, currentY);
  currentY += explanation.length * 6 + 10;

  // Features
  if (scanData.features && Object.keys(scanData.features).length > 0) {
    doc.setFontSize(14);
    doc.text("Features Analyzed", 20, currentY);
    currentY += 8;

    const features = Object.entries(scanData.features).map(([key, value]) => [
      key.replace(/([A-Z])/g, " $1").replace(/^./, (str) => str.toUpperCase()),
      typeof value === "boolean" ? (value ? "Yes" : "No") : value,
    ]);

    doc.autoTable({
      startY: currentY,
      head: [["Feature", "Value"]],
      body: features,
      theme: "striped",
      headStyles: { fillColor: [100, 100, 100] },
      margin: { left: 20, right: 20 },
      styles: { fontSize: 9 },
    });

    currentY = doc.lastAutoTable.finalY + 15;
  }

  // Recommendation
  doc.setFontSize(14);
  doc.setTextColor(220, 38, 38);
  doc.text("Security Recommendation", 20, currentY);
  currentY += 8;

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);

  let recommendation = "";
  if (scanData.riskScore > 70) {
    recommendation =
      type === "url"
        ? "CRITICAL: DO NOT proceed to this website. Report this URL to security authorities immediately."
        : "CRITICAL: DO NOT click any links or reply to this message. Block the sender immediately.";
  } else if (scanData.riskScore > 30) {
    recommendation =
      type === "url"
        ? "WARNING: Exercise caution. The URL shows suspicious characteristics. Verify before proceeding."
        : "WARNING: Be cautious. The message contains scam indicators. Do not share personal information.";
  } else {
    recommendation =
      type === "url"
        ? "SAFE: This website appears legitimate. Always remain vigilant."
        : "SAFE: This message appears legitimate. Always verify unexpected requests.";
  }

  const recLines = doc.splitTextToSize(recommendation, 170);
  doc.text(recLines, 20, currentY);

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} • Generated by PhishGuard Security System`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" },
    );
  }

  doc.save(`phishguard_report_${Date.now()}.pdf`);
};